#!/bin/sh

ENABLED=$(uci get ipt_ttl.config.enabled)
TTL=$(uci get ipt_ttl.config.ttl)

# Start clean
echo "# Generated by luci-app-ipt-ttl" > /etc/firewall.user

# Always remove old rules first to avoid duplication
{
    echo "# Clean up any existing TTL/HL rules"
    echo "iptables -t mangle -D PREROUTING -j TTL --ttl-set $TTL 2>/dev/null"
    echo "iptables -t mangle -D POSTROUTING -j TTL --ttl-set $TTL 2>/dev/null"
    echo "ip6tables -t mangle -D PREROUTING -i wwan0 -j HL --hl-set $TTL 2>/dev/null"
    echo "ip6tables -t mangle -D POSTROUTING -o wwan0 -j HL --hl-set $TTL 2>/dev/null"
    echo "ip6tables -t mangle -D PREROUTING -i wwan0_1 -j HL --hl-set $TTL 2>/dev/null"
    echo "ip6tables -t mangle -D POSTROUTING -o wwan0_1 -j HL --hl-set $TTL 2>/dev/null"
} >> /etc/firewall.user

# Apply TTL/HL rules only if enabled = 0
if [ "$ENABLED" = "0" ]; then
    {
        echo ""
        echo "# TTL/HL rules applied because ENABLED=0"
        echo "iptables -t mangle -A PREROUTING -j TTL --ttl-set $TTL"
        echo "iptables -t mangle -A POSTROUTING -j TTL --ttl-set $TTL"
        echo "ip6tables -t mangle -A PREROUTING -i wwan0 -j HL --hl-set $TTL"
        echo "ip6tables -t mangle -A POSTROUTING -o wwan0 -j HL --hl-set $TTL"
        echo "ip6tables -t mangle -A PREROUTING -i wwan0_1 -j HL --hl-set $TTL"
        echo "ip6tables -t mangle -A POSTROUTING -o wwan0_1 -j HL --hl-set $TTL"
    } >> /etc/firewall.user
fi
