#!/bin/sh

chmod 755 /etc/init.d/tailscale
chmod 755 /usr/sbin/tailscale_helper
chmod 755 /etc/hotplug.d/iface/40-tailscale

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@tailscale[-1]
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
